bug fixed
error: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result

fixed by:
Works fine with integers (numbers), for strings you need to put the
$variable in single quotes, like

$sql = "SELECT * FROM $usertable WHERE PartNumber = '$partid' ";